// ---------------------------------------------------------------------
// This file is part of falcon-core.
//
// Copyright (C) 2015, 2016, 2017 Neuro-Electronics Research Flanders
//
// Falcon-server is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Falcon-server is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with falcon-core. If not, see <http://www.gnu.org/licenses/>.
// ---------------------------------------------------------------------

#pragma once

#include <cassert>
#include <chrono>
#include <deque>
#include <limits>
#include <memory>
#include <string>

#include "ringbuffer.hpp"

#include "datatype_generated.h"
#include "flatbuffers/flatbuffers.h"
#include "flatbuffers/flexbuffers.h"
#include "logging/log.hpp"
#include "serialization.hpp"
#include "utilities/string.hpp"
#include "utilities/time.hpp"
#include "yaml-cpp/yaml.h"

/**
 * @brief The base class of AnyType::Data.
 */
class BaseData {};

/**
 * @brief The parent data type of AnyType.
 */
class BaseType {
   public:
    static const bool ispure() { return true; }
    using Data = BaseData;
};

/**
 * @brief Convenient template class to define data types.
 *
 * There are two required and three optional template arguments:
 * DATA: the associated data object class.
 * BASETYPE: the parent data type.
 * pure: optional, boolean argument indicating if data object
 * is pure (i.e., its members/parameters are independent from parent).
 * CAPS: optional, the capabilities class associated with the
 * data object class. Default is DATA::Capabilities.
 * PARAMS: optional, the parameters class associated with the
 * data object class. Default is DATA::Parameters.
 *
 * @note The class defines static datatype() and dataname() methods
 * that call the corresponding static methods in the data object class
 * it also defines a static ispure method that propagates up the hierarchy
 * (i.e., a data type is pure only if itself all its (grand)parents are pure.
 */
template <typename DATA, typename BASETYPE, bool pure = false,
          typename CAPS = typename DATA::Capabilities, typename PARAMS = typename DATA::Parameters>
class DefineType {
   public:
    static const std::string datatype() { return DATA::static_datatype(); }
    static const std::string dataname() { return DATA::static_dataname(); }

    static const bool ispure() { return pure && BASETYPE::ispure(); }

    using Data = DATA;
    using Parameters = PARAMS;
    using Capabilities = CAPS;
    using Base = BASETYPE;
};

/**
 * @brief Base class of all data object classes.
 *
 * We use CRTP with base class injection to define virtual member
 * functions that call the static member function in the derived class
 */
template <typename T, typename BASETYPE>
class IData : public BASETYPE::Data {
   public:
    using Base = typename BASETYPE::Data;
    using Base::Base;

   public:
    virtual std::string datatype() const { return T::static_datatype(); }
    virtual std::string dataname() const { return T::static_dataname(); }
};

namespace nsAnyType {

/**
 * @brief The Parameters structure is a container for parameters
 * used to initialize data object and provide an additional control over the
 * stored data.
 *
 * The parameterization is applied at the level of output ports,
 * but parameters can be customized for each slot.
 * The parameters are set during construction of the data objects.
 *
 * @note Parameters cannot be set for input ports
 * because they receive whatever is streamed from the upstream output port.
 */
struct Parameters {};

/**
 * @brief The Data class represent the datatype and what will be streamed
 * between input and output port.
 *
 * @property hardware_timestamp_ time at which data was generated by external
 * hardware
 * @property serial_number_ serial number of the data object
 */
class Data : public IData<Data, BaseType> {
   public:
    Data() : hardware_timestamp_(0), serial_number_(0) {}
    virtual ~Data() {}

    /**
     * @brief datatype
     * @return name of the datatype
     */
    static const std::string static_datatype() { return "any"; }
    /**
     * @brief dataname
     * @return label for the data
     */
    static const std::string static_dataname() { return "data"; }

    /**
     * @brief ClearData class is called each time
     * a data packet is claimed on the output port.
     *
     */
    virtual void ClearData() {}

    uint64_t serial_number() const;
    void set_serial_number(uint64_t n);

    /**
     * @brief This timestamp is set when the data packet is first
     * ingested by Falcon.
     *
     * @return int64_t
     */
    int64_t ingestion_ns() const;

    /**
     * @brief Set the ingestion timestamp to now. This should only be called
     * by a "source" processor when the data packet is first ingested.
     */
    void set_ingestion_ns();

    /**
     * @brief Forward the ingestion timestamp from an upstream data packet
     * to this data packet.
     */
    void forward_ingestion_ns(const Data& data);

    /**
     * @brief set_source_timestamp set the timepoint based on the internal
     * Falcon clock.
     */
    void set_source_timestamp();
    /**
     * @brief set_source_timestamp set a given timepoint.
     * @param t
     */
    void set_source_timestamp(TimePoint t);

    /**
     * @brief source_timestamp getter for the source_timestamp_.
     * This timestamp is set by the internal Falcon clock.
     *
     * @return TimePoint
     */
    TimePoint source_timestamp() const;

    /**
     * Compute the duration since the timestamp has been set.
     * The default unit is in microseconds but can be changed based
     * on the template.
     */
    template <typename DURATION = std::chrono::microseconds>
    DURATION time_passed() const {
        return std::chrono::duration_cast<DURATION>(Clock::now() - source_timestamp_);
    }

    /**
     * Compute the duration since the given reference.
     * The default unit is in microseconds but can be changed based
     * on the template.
     *
     * @param reference selected timepoint
     */
    template <typename DURATION = std::chrono::microseconds>
    DURATION time_since(TimePoint reference) const {
        return std::chrono::duration_cast<DURATION>(Clock::now() - reference);
    }

    /**
     * @brief hardware_timestamp timestamp given by the hardware. The unit
     * depends on the hardware.
     * @return
     */
    uint64_t hardware_timestamp() const;
    void set_hardware_timestamp(uint64_t t);

    /**
     * @brief CloneTimestamps - copy timestamps from one packet to the other
     * @param data
     */
    void CloneTimestamps(const Data& data);

    /**
     * @brief SerializeBinary - Serialize data specific for the data type in
     * binary form according to the layout described in YAMLDescription. At this
     * level, only serialize the source timestamp, hardware timestamp and serial
     * number.
     *
     * @param stream binary stream where to add the data
     * @param format Compact or Full
     */
    virtual void SerializeBinary(std::ostream& stream, Serialization::Format format) const;

    /**
     * @brief SerializeYAML - Serialize data specific for the data type in yaml
     * form according to the layout described in YAMLDescription. At this level,
     * only serialize the source timestamp duration, hardware timestamp and
     * serial number.
     *
     * @param node yaml node where to add the data
     * @param format compact or full
     */
    virtual void SerializeYAML(YAML::Node& node, Serialization::Format format) const;

    /**
     * @brief YAMLDescription - Add the datatype metadata (list of data with
     * type and size) to the header used for yaml and binary serialization.
     *
     * At this level add the source timestamp duration, hardware timestamp and
     * serial number format description.
     *
     * @param node - data node where to add a list of data element with the type
     * and the size
     * @param format compact or full
     */
    virtual void YAMLDescription(YAML::Node& node, Serialization::Format format) const;

    /**
     * @brief SerializeFlatBuffer - Serialize with a flexbuffer the data
     * specific for each datatype
     *
     * At this level add the source timestamp duration, hardware timestamp and
     * serial number format description.
     *
     * @param flex_builder flexbuffer builder
     */
    virtual void SerializeFlatBuffer(flexbuffers::Builder& flex_builder);

   protected:
    /**
     * @brief timestamp in nanoseconds when the data packet
     * was first ingested by Falcon.
     */
    int64_t ingestion_ns_;
    TimePoint source_timestamp_;
    uint64_t hardware_timestamp_;  // e.g. from Neuralynx
    uint64_t serial_number_;
};

/**
 * @brief The datatype capabilities is used to restrict the data object
 * parameterizations that an input port on a processor can handle.
 */

class Capabilities {
   public:
    /**
     * @brief Validate method is used to validate incoming data objects against
     * the capabilities. Capabilities are defined at the level of input ports
     * and all slots on a port share the same capabilities.
     *
     * @param prototype
     */
    void Validate(const Data& prototype) const {}
};

}  // namespace nsAnyType

/**
 * @brief The generic AnyType is the base of the datatype hierarchy.
 *
 * Data types are described by classes (such as the AnyType class)
 * that are just containers for the data object class and associated parameter
 * and capabilities classes, plus static member functions for the name of the
 * data type and a label for the data.
 *
 * The templated DefineType class is a convenient way to define a new
 * data type. If the Capabilities and Parameters classes are nested
 * inside the Data object class, then the last two template arguments
 * can be omitted.
 *
 * @note While there is an inheritance hierarchy for the data object classes,
 * there is no explicit hierarchy for the data type classes.
 */
using AnyType =
    DefineType<nsAnyType::Data, BaseType, true, nsAnyType::Capabilities, nsAnyType::Parameters>;
