debug:
  enabled: false
graph:
  autostart: false
  file: ''
logging:
  cloud:
    enabled: true
    port: 5556
  path: results/
  screen:
    enabled: true
network:
  port: 5555
server_side_storage:
  custom: {}
  environment: ./
  resources: ./resources
testing:
  enabled: false
